apiVersion: v1
kind: Secret
metadata:
  name: {{ include "mctagents.fullname" . }}-secrets
  labels:
    {{- include "mctagents.labels" . | nindent 4 }}
type: Opaque
stringData:
  postgres-password: {{ .Values.secrets.postgresPassword | quote }}
